language: java
sudo: required
jdk:
  - oraclejdk7

#  - oraclejdk8
#  - oraclejdk6
#  - openjdk8
#  - openjdk7
#  - openjdk6
#script: ./gradlew clean test

# enable codecov reporting...
after_success:
  - bash <(curl -s https://codecov.io/bash)


# Email notifications are disabled to not annoy anybody.
# See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
# about configuring notification recipients and more.
notifications:
  email: false


# enable gradle dependency caching...
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/